micronaut:
    application:
        name: foodguide
    metrics:
        enabled: true
    # Uncomment to set specific port
    #server:
    #    port: 8080

# Indent serialized JSON
jackson:
    serialization:
        indentOutput: true

# Enable health check endpoint
endpoints:
    health:
        details-visible: ANONYMOUS